### ISSUE TITLE
"Saving" doesn't seem to work

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3345]
## Description
When navigating to different sections, the form does not autosave.

## Steps to reproduce
1. Create a new form in the PR environment
2. Input a question
3. Navigate to "Test" or "Settings", etc.
4. Go back to "Edit"
5. See that it still says "Save Draft"

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
The form should auto-save when navigating away to different pages

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUhuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--217c36bd33fdbc9915a8690fc584b6639a263459/Screen%20Recording%202024-03-16%20at%205.55.51%E2%80%AFPM.mov)

## Additional context
Curious on when it should auto-save while a client works on the form? I thought we had something for that as well?

**Comment by dsamojlenko** [comment]
This should be fixed now: https://github.com/cds-snc/platform-forms-client/issues/3345

**Comment by Abi-Nada** [comment]
@dsamojlenko Re-tested and can confirm that it prompts the "Auto-Save" when I navigate to a different section!

I'm still not seeing the actual draft form saved under "Forms" - I'll relabel this issue under the "Forms" epic if maybe there's a connection there

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ZzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2afe8187e0efe3145662d0d56f6ea273445a0e4d/Screen%20Recording%202024-03-18%20at%201.33.52%E2%80%AFPM.mov)
